apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  labels:
    app: Create new scratch file from selection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Create new scratch file from selection
  template:
    metadata:
      labels:
        app: Create new scratch file from selection
    spec:
      containers:
        - name: frontend-container
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  labels:
    app: frontend-app
spec:
  type: LoadBalancer
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000